### ISSUE TITLE
Add support for rabbitmq-delayed-message-exchange

### ISSUE THREAD

**Issue by ldeluigi** [rebus-org/Rebus.RabbitMq#100]
Reading #56, I'm thinking that you should add (opt-in) support for the https://github.com/rabbitmq/rabbitmq-delayed-message-exchange plugin. At the present time, it is considered stable and is officially mantained by RabbitMq

**Comment by mookid8000** [comment]
Rebus' RabbitMQ can already work with the delayed message exchange plugin, it just requires a little bit of manual work.

You can see a small example here: https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq.Tests/Examples/CanSendDelayedMessageWithDelayedMessageExchangePlugin.cs#L57-L88

While working on the example I started sketching out a future version of the transport, which will add support for going

```csharp
services.AddRebus(
    configure => configure
        .Transport(t => t.UseRabbitMq(...))
        .Timeouts(t => t.UseDelayedMessageExchange("RebusDelayed"))
);

```

which will hook into all the right places to enable

```csharp
await bus.Defer(TimeSpan.FromSeconds(10), whatever);
```

But now it's Christmas 🎄 🎅 and I've stashed my work, so I'll continue some time in a couple of weeks probably (or tomorrow, maybe...)

**Comment by mookid8000** [comment]
OK I already added the feature as described above. It's available in Rebus.RabbitMq 7.4.6 which is on NuGet.org now
