### ISSUE TITLE
Old RabbitMq.Client version

### ISSUE THREAD

**Issue by EvgenyGrishnov** [rebus-org/Rebus.RabbitMq#101]
Good day
I see that referenced version is:
<PackageReference Include="RabbitMq.Client" Version="6.2.4" />

When the latest version is 6.4.0
It has few tweaks and fixed.

I think that Rebus.RabbitMq shoud be syncronized with RabbitMq.Client somehow

**Comment by mookid8000** [comment]
Rebus.RabbitMq 7.4.3 (which is on Nuget.org now) has been updated to reference RabbitMq.Client 6.4.0 🙂
