### ISSUE TITLE
RabbitMq client version 6.4.0 should be analized before integrated in project

### ISSUE THREAD

**Issue by EvgenyGrishnov** [rebus-org/Rebus.RabbitMq#102]
Good day.

There is some problem: version 6.2.4 has few fixes, tweaks that should be analyzed before they will be applied into Rebus.RabbitMq

For example: 
"AutorecoveringModel.IsClosed should return true if model is unusable" is this fix affects on RabbitMqTransport.cs?
"Add TimeOut to Abort call in dispose" now abort method has 30 seconds timeout instead of Timeout.Infine. Does it matters?

Rebus.RabbitMq used in enterprise solutions and so there is expectation that code can be used in real systems safely because it works as expected by Rebus team.

**Comment by mookid8000** [comment]
I don't understand... is there a problem with the newest Rebus.RabbitMq 7.4.3 (which has had its RabbitMq.Client dependency updated to 6.4.0)?

**Comment by EvgenyGrishnov** [comment]
No, there is no problems for now )) 
I am just trying to say that transition from 6.2.4 to 6.4.0 has a almost 4 months history of changes (from march till june). 
And if you reviewed changes since 6.2.4 before applying them into rebus then ok. 
We are using rebus in banking application and I'm trying to figure out how much I can rely on the reliability of the library when I decide to apply updates.

**Comment by mookid8000** [comment]
Yeah well, people are using Rebus for all kinds of important stuff. 

No matter what you're building, if it's important, then you should be sure to have proper QA environments and procedures in place - but I bet you have that already. 🙂 

That's really all I can say. 

As with all free software, even though the maintainers do their best, you cannot have any kind of guarantees regarding whether updates will break your stuff.  But again, I bet that can be said about many of the libraries you are building your stuff on.

If you're interested in having a lifeline IF something does break, I suggest you take a look at [Rebus Pro](https://pro.rebus.fm/).
