### ISSUE TITLE
Dependency constraint should be updated

### ISSUE THREAD

**Issue by boskjoett** [rebus-org/Rebus.RabbitMq#103]
When I use the latest versions of Rebus (7.0.0) and Rebus.RabbitMQ (7.4.6) NuGet packages I get this compiler warning

Warning	NU1608	Detected package version outside of dependency constraint: Rebus.RabbitMq 7.4.6 requires rebus (>= 6.0.0 && < 7.0.0) but version Rebus 7.0.0 was resolved.

I guess the dependency constraint of Rebus.RabbitMQ needs to be updated

**Comment by mookid8000** [comment]
Hi @boskjoett , sorry! 😅 It's been updated in Rebus.RabbitMq 8.0.0, which is on NuGet.org now
