### ISSUE TITLE
Support for V5 of RabbitMQ.Client

### ISSUE THREAD

**Issue by lkt82** [rebus-org/Rebus.RabbitMq#11]
Hi :)

Would it be possible to update the library to support the latest V5 RabbitMQ.Client dependency ?.

Currently V5 breaks rebus because ConnectionFactory.Uri was changed to a URI type instead of a string

Cheers

**Comment by dougkwilson** [comment]
I'll work on this.

**Comment by mookid8000** [comment]
it's out as Rebus.RabbitMq 4.4.0 in a few minutes 😄 

(PS: I chose to only bump the minor version, because the change is not breaking as seen from the consumer of Rebus.RabbitMq.... don't know if it's right to do so.... I hope it's alright 😁 )

**Comment by dougkwilson** [comment]
@mookid8000... you make it so easy!!  Thanks!

**Comment by mookid8000** [comment]
@dougkwilson I could say the same thing about you 🙂
