### ISSUE TITLE
Specifying a consumer tag

### ISSUE THREAD

**Issue by savissimo** [rebus-org/Rebus.RabbitMq#112]
I have found no way to specify a custom consumer tag. Client properties are cool, but a consumer tag would help identifying the consumer in a more immediate way. 

Since consumer tags must be unique, the user could specify a prefix (say `myApp`) and the actual consumer would append a random string (`myApp-f88efnax`). 

If you wish, I could take care of the changes myself.

**Comment by mookid8000** [comment]
Oh, I wasn't familiar with the concept of consumer tags. Sounds like it would be fairly straightforward to add in a way similar to how client properties are added.

Would be lovely with a PR 🙂

**Comment by mookid8000** [comment]
Fixed by you in #115 😉  - out as Rebus.RabbitMq 9.3.0 on NuGet.org now 🙂
