### ISSUE TITLE
How can I get RebusHeaders exchange in RabbitMQ via Rebus?

### ISSUE THREAD

**Issue by galloglach** [rebus-org/Rebus.RabbitMq#119]
What do I need to do to get a RebHeaders exchange created in RabbitMQ when using Rebus.
I can get a RebusTopics exchange created which is of type "topic".
![image](https://github.com/rebus-org/Rebus.RabbitMq/assets/2843801/d3c3e74f-0a45-4de4-83c5-6ac16f211f5b)

**Comment by mookid8000** [comment]
Rebus doesn't support headers exchanges. 😐 

What did you want to use it for?

**Comment by galloglach** [comment]
Topics exchange seems to be too restrictive, where there is just the one string that the queues bind by.
The [Headers exchange](https://www.cloudamqp.com/blog/part4-rabbitmq-for-beginners-exchanges-routing-keys-bindings.html#headers-exchange) seems to be more flexible in that a message is published to the exchange with x different header values and queues can bind on a specific header value via "x-any".

**Comment by galloglach** [comment]
An `Event` has a characteristic such as `Date` and depending on it value I'd like it to go to different queue.
For instance, if there were 4 queues, _Within24Hours_, _Within7Days_,  _Within30Days_ & _Within365Days_, the same `Event` message would go to the appropriate queues.

So for an `Event` that is occurring in 6 hours time then it would go to all the queues.
An `Event` that is occurring in 2 weeks time then it would only go to all the _Within30Days_ & _Within365Days_ queues.

In scenario 1 (6 hours) the message would be published with these header values `{ Within24Hours:1, Within7Days:1, Within30Days:1, Within365Days:1 }`.
In scenario 2 (2 weeks) the header values would be `{ Within30Days:1, Within365Days:1 }`.

**Comment by galloglach** [comment]
Thanks for that info, it gives me another avenue to explore.

Just one follow up question :-)

It looks like I should be able to create a HeadersExchange (_MyHeaders_) in RabbitMQ, bind it to the _RebusTopics_ exchange using the _#_ routing pattern and then have the queues (_Within24Hours_, _Within7Days_, Within30Days_ & _Within365Days_) bind to  _MyHeaders_ exchange using appropriate arguments.
In that case are the headers that I send when publishing to _RebusTopics_ sent on to _MyHeaders_ exchange?

**Comment by mookid8000** [comment]
I think so, yes 🙂 but please make sure to have integration tests in place that exercise these things in particular. Sendt fra min iPhone–Mogens Heller GrabeTorsmark 48700 HorsensDanmark+45 ***@***.*** 29. feb. 2024 kl. 19.04 skrev gallowglass ***@***.***>:﻿
Thanks for that info, it gives me another avenue to explore.
Just one follow up question :-)
It looks like I should be able to create a HeadersExchange (MyHeaders) in RabbitMQ, bind it to the RebusTopics exchange using the # routing pattern and then have the queues (Within24Hours, Within7Days, Within30Days_ & Within365Days) bind to  MyHeaders exchange using appropriate arguments.
In that case are the headers that I send when publishing to RebusTopics sent on to MyHeaders exchange?
