### ISSUE TITLE
One of ConnectionManager constructors ignores TLS settings

### ISSUE THREAD

**Issue by yuriyostapenko** [rebus-org/Rebus.RabbitMq#120]
Thanks for the great library!

I am currently trying to make it work over TLS and encountered the following problem:
```csharp
var bus = Configure.With(activator)
    .Logging(l => l.Console())
    .Transport(t => t.UseRabbitMq($"amqps://{username}:{password}@host:port/", "test-queue"))
    .Start();
```

fails with error:
```
Exception thrown: 'RabbitMQ.Client.Exceptions.BrokerUnreachableException' in RabbitMQ.Client.dll: 'None of the specified endpoints were reachable'
 Innermost exception 	 System.IO.IOException : connection.start was never received, likely due to a network timeout
...
```

This happens due to `ConnectionManager` not configuring endpoints correctly. In this case, original connection string has the right schema and host name, yet an `AmqpTcpEndpoint` created here
https://github.com/rebus-org/Rebus.RabbitMq/blob/240baa55148cfbe8d6b90b26532227ba2a146584/Rebus.RabbitMq/Internals/ConnectionManager.cs#L129
does not get its `SslOptions` initialized.

The other constructor initializes them properly
https://github.com/rebus-org/Rebus.RabbitMq/blob/240baa55148cfbe8d6b90b26532227ba2a146584/Rebus.RabbitMq/Internals/ConnectionManager.cs#L76
so if another `UseRabbitMq` overload is used (the one taking `IList<ConnectionEndpoint> endpoints`), everything seems to work.

Workaround:
```csharp
var uri = new Uri($"amqps://{username}:{password}@host:port/");
var bus = Configure.With(activator)
    .Logging(l => l.Console())
    .Transport(t => t.UseRabbitMq(
                        new[] {
                            new ConnectionEndpoint()
                            {
                                ConnectionString = uri.ToString(),
                                SslSettings = new SslSettings(true, uri.Host /* required for SNI to work */)
                            }
                        },
                        "test-queue")
                    )
    .Start();
```
---
I would gladly submit a PR to fix this, but I am a bit puzzled by the problematic constructor supporting multiple endpoints and I do not understand how it's supposed to be used, so as to not break that flow. I also am not sure how that has to co-exist with `customizer`. Any customizations to connection settings seem to be ignored by current code.

**Comment by yuriyostapenko** [comment]
The complication is that there are potentially more useful advanced configuration options, besides just "tls on/off", such as protocol version, SNI hostname, trust settings and so on that are not encodable in the uri string, but can be set up in customizer.

And such customizations, while unlikely, may need to be different per endpoint.
But yes, at least a basic scheme based condition will fix 90% TLS support scenarios.

**Comment by mookid8000** [comment]
It's fixed in Rebus.RabbitMq 9.1.0, which is on NuGet.org now 🙂
