### ISSUE TITLE
Not compatible with RabbitMQ.Client nuget 5.x?

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus.RabbitMq#19]
I updated my nuget packages and got version 5.0.1 of (https://www.nuget.org/packages/RabbitMQ.Client/5.0.1) the RabbitMQ.Client.

Here is the exception I got during startup:

-		InnerException	{"An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IBus (DelegateActivator), Services = [Rebus.Bus.IBus], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Could not resolve Rebus.RabbitMq.RabbitMqTransport with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler (See inner exception for details.)"}	System.Exception {Autofac.Core.DependencyResolutionException}

+		InnerException	{"Could not resolve Rebus.RabbitMq.RabbitMqTransport with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler"}	System.Exception {Rebus.Injection.ResolutionException}

+		InnerException	{"Method not found: 'Void RabbitMQ.Client.ConnectionFactory.set_Uri(System.String)'."}	System.Exception {System.MissingMethodException}

The fix was downgrading to version 4.1.3.
I tested with both version 4.2 and version 4.3 of Rebus.RabbitMq

**Comment by mookid8000** [comment]
Yeah well, looks like #11 has not been solved yet 😄 

(closing this one because #11 pretty much nails it)
