### ISSUE TITLE
What happened to ManageSubscriptions() ?

### ISSUE THREAD

**Issue by NKnusperer** [rebus-org/Rebus.RabbitMq#2]
The [rabbitmq transport article](https://github.com/rebus-org/Rebus/wiki/Rabbitmq-transport) in the wiki claims that there should be a `ManageSubscriptions()` extension method. However in the current version it doesn't seem to exist.

**Comment by mookid8000** [comment]
It's gone because the current Rebus will always use RabbitMQ's multicast features.

This also means that the `.Subscriptions(s => ....)` configuration is not necessary when using RabbitMQ.
