### ISSUE TITLE
Could not resolve Rebus.Bus.Ibus with decorator depth -1

### ISSUE THREAD

**Issue by doctorssm** [rebus-org/Rebus.RabbitMq#21]
Hi! During startup, the RabbitMQ connection string is not responding Rebus can't start.

 using (var publisher = new BuiltinHandlerActivator())
                {
                    var publisherBus = Configure.With(publisher)
                        .Options(o => o.LogPipeline())
                        .Transport(t => t.UseRabbitMqAsOneWayClient("amqp://EventNetClient:Password1@localhost:5672"))
                        .Routing(r => r.TypeBased().MapAssemblyOf<TestModel>("EventNet Event Delta"))
                        .Start();

                    var testModel = new TestModel { Name = "Three" };

                    publisherBus.Send(testModel);

                }

I get next exception: Could not resolve Rebus.Bus.Ibus with decorator depth -1
details: https://www.screencast.com/t/CuBofCph02

I have installed all necessary dependencies with last versions.

**Comment by mookid8000** [comment]
It says 

    access to queue 'error' in vhost '/' refused for user 'EventNetClient'

I bet that's the problem.
