### ISSUE TITLE
Extend optionsBuilder with RabbitMqExchangeOptionsBuilder

### ISSUE THREAD

**Issue by hansehe** [rebus-org/Rebus.RabbitMq#34]
It would be very convenient to be allowed to extend the exchange configuration.
As with queues, it is possible to extend the queue configuration with RabbitMqQueueOptionsBuilder, so it should be possible to do the same with exchanges.

Thus, introducing RabbitMqExchangeOptionsBuilder

**Comment by mookid8000** [comment]
Solved by #31
