### ISSUE TITLE
Null reference in RabbitMqTransport.CreateTransportMessage

### ISSUE THREAD

**Issue by tbue** [rebus-org/Rebus.RabbitMq#35]
Hi, we found an issue in the CreateTransportMessage method. We fetched a message from a queue and it had a null as value in one of the headers. This meant that the headerValue.ToString() throws a null reference.

We would like to see that changed to something like headerValue?.ToString() ?? string.Empty - and see a released dll with that fix.

Thanks

**Comment by mookid8000** [comment]
it's out in Rebus.RabbitMq 5.0.0-b05
