### ISSUE TITLE
Check if RabbitMq queue exists before creating it

### ISSUE THREAD

**Issue by pravinkarthy** [rebus-org/Rebus.RabbitMq#50]
Hi @mookid8000 ,

Am using two RabbitMQTransport objects, one as one-way sender and another as receiver queue.
(1) Is it possible to check if the receiver queue exists using the "queuename" before creating it.
(2) Also, wanted to check if its possible to selectively delete a message from rabbitmq by fetching the transportMessage object based on MessageID or any other attribute ?

Thanks.

**Comment by mookid8000** [comment]
1) Rebus does that for you – it uses the [`QueueDeclarePassive`](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq/RabbitMq/RabbitMqTransport.cs#L665) command the first time it sees a new destination queue, so it will fail if you try to send to a non-existent queue.

2) I don't think that's possible. As far as I know, RabbitMQ only provides the ability to dequeue the next message.

**Comment by pravinkarthy** [comment]
thanks a lot !
