### ISSUE TITLE
Support adding `clientProvidedName` to Rabbit's ConnectionFactory

### ISSUE THREAD

**Issue by hulvei3** [rebus-org/Rebus.RabbitMq#52]
For debugging purposes, it would be nice to have the option to "label" the connections created with Rebus. This is supported through [rabbitmq client](https://rabbitmq.github.io/rabbitmq-dotnet-client/api/RabbitMQ.Client.ConnectionFactory.html#RabbitMQ_Client_ConnectionFactory_CreateConnection_System_String_) and could be defaulted to the assembly or namespace - or not.

This properly fits directly into the `ConnectionManager` unless there's a better way of grouping the properties to rabbit

**Comment by mookid8000** [comment]
That's actually already possible 😄  – check this out:

```csharp
Configure.With(activator)
    .Transport(t =>
    {
        t.UseRabbitMq(RabbitMqTransportFactory.ConnectionString, queueName)
            .AddClientProperties(new Dictionary<string, string>
            {
                {"description", "pub-sub test in RabbitMqPubSubTest.cs"}
            });
    })
    .Start();
```

(taken from [RabbitMqPubSubTest.cs](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq.Tests/RabbitMqPubSubTest.cs))

**Comment by mookid8000** [comment]
Sorry for closing... I thought I had the answer, but I was too quick there. 

That would indeed be a nice feature 😄 

Defaulting to the entry assembly or something similar would definitely be neat. It could then be customized in the [same way as client properties are configured](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq.Tests/RabbitMqPubSubTest.cs#L76) (did you know that that was possible?)

**Comment by hulvei3** [comment]
Yes, that would be a natural place to put it. Let me see if I cannot find time to make a PR within the next days..

**Comment by jarikp** [comment]
hi @hulvei3 ,
you can achieve that by decorating the connection factory, as it's shown in my PR.
/Jarik

**Comment by mookid8000** [comment]
Note to future self or someone else: When RabbitMq.Client 6 is released, this can be easily solved. 🙂

**Comment by hulvei3** [comment]
Actually, I solved this by using `.ClientConnectionName(..)` on the RMQ configurer object. Not sure why I missed that a year ago. Maybe it was added afterwards.

Will anyway close this issue.
