### ISSUE TITLE
Why Rebus.Timeouts.ITimeoutManager is not Implemented?

### ISSUE THREAD

**Issue by xyfy** [rebus-org/Rebus.RabbitMq#56]
Why Rebus.Timeouts.ITimeoutManager is not Implemented?

And When you plan to do this?

I want to use the defer message in rabbitmq

or anything I can do ?

**Comment by mookid8000** [comment]
What makes you think it's not implemented?

**Comment by xyfy** [comment]
I donnot found it in the source code ,but I found a Implemented in `Rebus.SqlServer`

I tried to use the `UseExternalTimeoutManagerto` defer message 

but it don't be affected

I start another bus to subcribe the defer queue like code below
``` csharp
rebusConfig.Timeouts(t => t.UseExternalTimeoutManager(Consts.MqDeferQueue));
                //rebusConfig.Timeouts(t => t.StoreInSqlServer(Configuration.DefaultNameOrConnectionString, "Rebus_Mq_Timeouts", true));//利用数据库进行倒计时

                _bus = rebusConfig.Start();
                //延时消息必备配置 start
                using (var active = new BuiltinHandlerActivator())
                {
                    var deferConfig = Configure.With(new BuiltinHandlerActivator());
                    deferConfig.Logging(moduleConfig.LoggingConfigurer);
                    deferConfig.Transport(t => t.UseRabbitMq(Consts.MqConnnectionString, Consts.MqDeferQueue));
                    deferConfig.Routing(c =>
                    {
                        var typebaseRouting = c.TypeBased();
                        foreach (var mqMessageType in mqMessageTypes)
                        {
                            typebaseRouting.Map(mqMessageType, Consts.MqDeferQueue);
                        }
                    });

                    deferConfig.Timeouts(t => t.StoreInMemory());
                    //deferConfig.Timeouts(t => t.StoreInSqlServer(Configuration.DefaultNameOrConnectionString, "Rebus_Mq_Timeouts", true));
                    deferConfig.Start();
                }
```
It worked。
However, I found that I did not actually use this delay queue at all. It just use `Rebus.SqlServer` to poll the table to achieve it. 
it's nothing go on in [MqDeferQueue]

**Comment by xyfy** [comment]
Then I try to go to source , I have not found a class that Implement `Rebus.Timeouts.ITimeoutManager ` in `Rebus.RabbitMq`, Is there anything wrong with me ?

**Comment by mookid8000** [comment]
RabbitMQ is not capable of sending messages with individual delays – that's the reason why Rebus' RabbitMQ transport does not provide an implementation.

**Comment by xyfy** [comment]
I don't know why 

but today I try to use the RabbitMQ  Plugin  [rabbitmq-delayed-message-exchange](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange) which offered by RabbitMQ  ,that worked fine. 

I am looking for a way to use it with `Rebus.RabbitMq` together now.

**Comment by mookid8000** [comment]
> but today I try to use the RabbitMQ Plugin rabbitmq-delayed-message-exchange which offered by RabbitMQ ,that worked fine.
>
> I am looking for a way to use it with Rebus.RabbitMq together now.

I didn't know that plugin existed. You might be able to put it to use with Rebus by providing a `x-delay` header on your messages, e.g. like this:
```csharp
var headers = new Dictionary<string, string> {{"x-delay", "5000"}};

await bus.Send(new SomeMessage(), headers);
```
although I'm not completely sure that the RabbitMQ plugin will correctly pick up the value.

**Comment by mookid8000** [comment]
I hope this answered your question. I'm closing the issue for now.
