### ISSUE TITLE
content_type of RabbitMQ message

### ISSUE THREAD

**Issue by marrrschine** [rebus-org/Rebus.RabbitMq#60]
Hi! First at all, awesome project!

I'm using Rebus and Rebus.RabbitMq (5.1.3) with .NET Core 2.2.
One question concerning the `content_type` of a rmq message, which is `application/json;charset=utf-8` by default. Can I change this to just `application/json`? 
Thanks!

**Comment by mookid8000** [comment]
fixed in Rebus.RabbitMq 5.2.0, which is on Nuget.org now 🙂
