### ISSUE TITLE
Topology

### ISSUE THREAD

**Issue by jok-l** [rebus-org/Rebus.RabbitMq#61]
At first, i have to say thanks for you work, Rebus is a shining library ;)

Are there extension points to change the exchange/queue/bindings topology?

We want to create a topology more like the conventional one from NServiceBus:
https://jack-vanlightly.com/blog/2017/3/16/default-topologies-nservicebus-with-rabbitmq-part-2

There are "general queues" for "IEvent" (our events are based on an interface too) and "object". With this, we plan to create a specialized service for monitoring our system.

Edit:
I found the option to enable the message auditing ;) Now, all messages are (also) routed to the audit queue; but currently i can't receive them. I tried different message handlers:

- IHandleMessages&lt;JObject&gt;
- IHandleMessages&lt;object&gt;
- IHandleMessages&lt;IEvent&gt; (all our events implement IEvent)

Everytime i get an exception "Rebus.Exceptions.MessageCouldNotBeDispatchedToAnyHandlersException - Message with Id {bla} and type {blub} could not be dispatched to any handlers"

**Comment by mookid8000** [comment]
Regarding topology options: Rebus does not really support anything besides its own two-exchange topology, where one is for direct routing, and the other one is for pub/sub. 

If your motivation for changing the topology is to get copies of all published and handled messages, then I am happy that you figure out how to enable auditing 🙂 

If your messages contain JSON, then it should be possible for you to handle them using an implementation of `IHandleMessages<JObject>` – you just need to ensure that your handler is resolved from your IoC container, when Rebus asks it to "give me all handlers that implement IHandleMessages<JObject>" (differs from container to container – some `ResolveAll<IHandleMessages<JObject>>`, some `Resolve<IEnumerable<IHandleMessages<JObject>>>`, etc.)

Could you check your container and see if it can resolve your handler?

There's also another option, which is more low-level, and has much more generic potential: Handling audited messages in a "transport message forwarder". You can read about them here on the wiki page: [Transport message forwarding](https://github.com/rebus-org/Rebus/wiki/Transport-message-forwarding).

As you can see, a transport message forwarder gets access to the raw `byte[]` of the incoming transport message, and it doesn't spend time deserializing etc., so if that's what you really want, then this is how to get it 🙂

**Comment by jok-l** [comment]
Sorry, for writing once more.

One motivation is to get copies of all messages, surely i am able to figure out, why currently my IoC container is not resolving the handler. But the other motivation is performance. My supervisor is in doubt if the evaluation of all the topic keys (one per event) is fast enough in a more complex system?

Now, i am instructed to evaluate the possibility to change the Rebus topology. Do you think it is even possible? I think, reimplementing "IRouting" and "ITransport" should do the trick?

**Comment by mookid8000** [comment]
If you implement `IRouter`, `ITransport`, and `ISubscriptionStorage`, you can do anything you want 🙂 all the specifics of how queues, topics, exchanges and bindings are managed are implemented in `ITransport` (to send messages), `ISubscriptionStorage` (to manage topics & bindings)`, and in `IRouter` (to decide how "sending" and "publishing" messages maps to specific topics and queue names).

I suggest you try to go with the default transport implementation though, and then evaluate its performance. If you then decide that something could be better, then come back here and talk to me about it – then we'll see if it's something that ought to be fixed in Rebus instead.

**Comment by jok-l** [comment]
May i ask one more question? Played around with this awesome packet, tried to implement the other topology (and it sort of works). But it's complicated and dangerous, i think. So i try to achieve our goals with the "build-in" transport.

> If your messages contain JSON, then it should be possible for you to handle them using an implementation of IHandleMessages&lt;JObject&gt;

If i view my messages in the rabbit mq admin panel, the body is json. But my generic handler ": IHandleMessages&lt;JObject&gt; is not called, because in the "DeserializeIncomingMessageStep" the json serializer is throwing an exception, because he can not find the .net type to deserialize the message to. Sure, because we don't want all message contracts in our audit service.
For such a generic handling of the messages; is the way to go the "transport message forwarder" you mentioned?

**Comment by mookid8000** [comment]
Sorry, I realize now that I might have been referring to something, which Rebus used to be capable of, but apparently isn't anymore.

Sorry about that!

But... it's fairly easy to accomplish what you want, and I think the best way would probably be to implement your own JSON serializer.

Rebus' `ISerializer` interface is pretty simple, and you can register your implementation like this:
```csharp
Configure.With(...)
	.(...)
	.Serialization(s => s.Register(c => new MyJsonSerializer()))
	.Start();
```
although you might want to hide the `s.Register(...)` part behind an extension method, so it can look like this:
```csharp
Configure.With(...)
	.(...)
	.Serialization(s => s.UseMyJsonSerializer())
	.Start();
```
where `UseMyJsonSerializer` then hides "the magic":
```csharp
public static CustomRebusConfigurationExtensions 
{
	public static void UseMyJsonSerializer(this StandardConfigurer<ISerializer> configurer)
	{
		configurer.Register(c => new DynamicJsonSerializer());
	}
}
```

Your serializer would then provide the necessary deserialization somewhat like this:
```csharp
public class MyJsonSerializer : ISerializer
{
	public async Task<TransportMessage>(Message message)
	{
		throw new InvalidOperationException("This serializer cannot serialize, as it will only be used to RECEIVE messages");
	}

	public async Task<Message>(TransportMessage transportMessage)
	{
		var headers = transportMessage.Headers.Clone();
		var body = JObject.Parse(Encoding.UTF8.GetString(transportMessage.Body));

		return new Message(headers, body);
	}
}
```
which you would of course pimp a little bit, if you wanted it to support multiple encodings, etc.

Do you think that would be useful for you?

**Comment by jok-l** [comment]
> Do you think that would be useful for you?
Absolut. I started to implement our monitoring system with the message forwarder you mentioned some posts above, but there are some sorts of other problems (eg. it's just a function, so no service injections).
The solution using a specialized serializer to me is more appealing, because then it's works like "normal" message handler. I definitifely try this out the next days.

Thanks for your time and work!
