### ISSUE TITLE
Add ability to subscribe to topics on explicitly specified exchanges

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus.RabbitMq#65]
similar to how
```csharp
await bus.Advanced.Topics.Publish("some-topic@some-exchange", whatever);
```
will publish to the `some-exchange` exchange, it should be possible to
```csharp
await bus.Advanced.Topics.Subscribe("some-topic@another-exchange");
```
if that's what you want.

**Comment by mookid8000** [comment]
will be out in Rebus.RabbitMq 6.1.0 as soon as the buildserver finishes munching through the tests 🙂

**Comment by dekim** [comment]
Awesome, thanks for your awesome work <3
