### ISSUE TITLE
Bumping Rebus to verstion 6.4.1?

### ISSUE THREAD

**Issue by renemadsen** [rebus-org/Rebus.RabbitMq#74]
Could we get this one bumped to version 6.4.1 of Rebus ?

**Comment by mookid8000** [comment]
If you want to use 6.4.2, you can just install that in your project.... 🤔

**Comment by renemadsen** [comment]
It's because in the project, we rely on Rebus.CastleWindsor and they use Rebus.RabbitMq, and since they are not both using Rebus 6.4.1 it gives some funny conflicts, which will not be there, when they both use the same Rebus version.

Hope it makes sense?

**Comment by mookid8000** [comment]
You should be able to solve that by installing Rebus 6.4.1 explicitly in your project

**Comment by renemadsen** [comment]
> You should be able to solve that by installing Rebus 6.4.1 explicitly in your project

It should work, but I rather don't have mixed versions in our projects.

I made a fork and upgraded packages, so it's now ready for you to release after your own testing.

https://github.com/renemadsen/Rebus.RabbitMq

Also did fix the tests so it's ready for net 5.0, had to remove net461, to make it build on github actions (way faster build times than AppVeyor) and added dependabot, so it was easy to test package upgrades, before updating dependencies.

It should be fairly easy to cherrypick a PR if you like, so it's working with net461 also.

**Comment by mookid8000** [comment]
Hi @renemadsen , did you figure it out?

It should be possible to install any 6.* version of Rebus as a dependency of your entry point project. If that is not the case, feel free to pick up this issue again.

**Comment by renemadsen** [comment]
> Hi @renemadsen , did you figure it out?
> 
> It should be possible to install any 6.* version of Rebus as a dependency of your entry point project. If that is not the case, feel free to pick up this issue again.

Since we are using a plugin structure with mvc and backgroup services, it needs to be the same versions of Rebus in all parts otherwise C# creates weird errors at runtine doing dll version lookup.

So in order to avoid this kind of problem, all parts, which is using Rebus needs to be using the same exact version of Rebus.
