### ISSUE TITLE
Connection issue when run long-lived service

### ISSUE THREAD

**Issue by volethanh** [rebus-org/Rebus.RabbitMq#81]
Hi,

I've got this issue when I use Rebus.RabbitMq in WebAPI (.NET 5).

I run my WebAPI for several days and suddenly the connection between WebAPI and RabbitMq is shutdown. When I restarted, it ran again and it would stop for several days.

This is my log when the service is stop and I only know when I try call the API

<img width="1096" alt="Screen Shot 2021-06-17 at 11 50 51 AM" src="https://user-images.githubusercontent.com/46510130/122333403-4c5f7100-cf62-11eb-8a7b-da0a04cb88f3.png">

**Comment by mookid8000** [comment]
Hmm that's weird. Are you using the latest Rebus.RabbitMq?

As far as I know, the RabbitMq.Client driver should be able to resolve connection issues by itself since [this property](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq/Internals/ConnectionManager.cs#L66) is set.... 🤔

**Comment by volethanh** [comment]
I'm using the latest Rebus.RabbitMq and I always get error. 

<img width="994" alt="Screen Shot 2021-07-02 at 10 41 38 AM" src="https://user-images.githubusercontent.com/46510130/124217296-5072bd80-db22-11eb-81fe-709dfa089257.png">

The workaround is restart the web or the service but it will cause error again

**Comment by mookid8000** [comment]
OK so it never recovers, when that error has shown up?

**Comment by mookid8000** [comment]
Could you try Rebus.RabbitMq 7.3.1-b7 and see if it makes a difference?

**Comment by mookid8000** [comment]
Hi again @volethanh , I think there has been several improvements in this area, the latest being Rebus.RabbitMq 7.3.1-b11

Could you maybe try it and see if it fixes your problem?

**Comment by volethanh** [comment]
> Hi again @volethanh , I think there has been several improvements in this area, the latest being Rebus.RabbitMq 7.3.1-b11
> 
> Could you maybe try it and see if it fixes your problem?

sorry for late reply, ok @mookid8000 , I will try that version to see if it fixed. 

Right now, I modified a bit by using Polly for retry mechanism and this work properly.
